### ISSUE TITLE
你好，请问如果我要使用GMAN_generateSE.py生成PEMS0X(比如PEMS04、PEMS07)数据集的SE_pems04.txt该如何做呢

### ISSUE THREAD

**Issue by serenaand** [deepkashiwa20/DL-Traff-Graph#2]
我应该如何替换这两个文件呢
FLOWPATH = '../PEMSBAY/pems-bay.h5'
ADJPATH = '../PEMSBAY/W_pemsbay.csv'

**Comment by deepkashiwa20** [comment]
你好 GMAN_generateSE.py里面大概是写了是对着邻接矩阵这个文件用了node2vec去生成node embedding (SE, spaital embedding)，所以得先找到pems04 07的邻接矩阵替换就好。主要是替换这个W_pemsbay.csv文件^_^

**Comment by serenaand** [comment]
好的 谢谢啦

**Comment by deepkashiwa20** [comment]
不客气噢
